@baseUrl = http://localhost:8000

### Crear board
POST {{baseUrl}}/boards/createBoard
Content-Type: application/json
Accept: application/json

{
  "title": "New Board"
}

### Test validación incorrecta
POST {{baseUrl}}/boards/createBoard
Content-Type: application/json
Accept: application/json

{
  "title": 2
}

### Test seteo datos
PUT {{baseUrl}}/boards/updateBoard
Content-Type: application/json
Accept: application/json

{
  "id": "cmg0y2x2f0001gdihaj2v280v",
  "data": {
    "cards": [
      {
        "title": "testCard2",
        "description": "Description for test card"
      }
    ],
    "containers": [
      {
        "title": "testContainer",
        "cards": [
          0
        ]
      }
    ],
    "containersOrder": [0]
  }
}

### Test de GET a un board
GET {{baseUrl}}/boards/getBoard?id=cmg0y2x2f0001gdihaj2v280v

### Borrar un board
DELETE {{baseUrl}}/boards/deleteBoard
Content-Type: application/json
Accept: application/json

{
    "id": "asd"
}

### Ver todos los boards
GET {{baseUrl}}/boards/getAllBoards